- name: Hello World Sample
  hosts: Nagios
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
- name: test ping
  hosts: Centreon
  tasks:
    - name: Ping Pong
    ping:
