- name: Hello World
  hosts: Nagios
  tasks:
    - debug:
        msg: "Hello World!"
        
- name: Test Ping
  hosts: Centreon
  tasks:
    - ping:
      
- name: Test Module
  hosts: all
  tasks:
    - test:
      register: res
      
    - debug: var=res
